### ISSUE TITLE
Upgrading to 1.208 breaks the module

### ISSUE THREAD

**Issue by webtoolbox** [genio/digest-bcrypt#4]
On Ubuntu 14.04 LTS, we have one server using 1.207 and that works fine. Our same code on a different server with version 1.208 of Digest::Bcrypt fails with this error:
"Salt must be exactly 16 octets long"

The code has been used for months without any issue. Downgrading back to 1.207 makes the code work again without throwing any error.

Data::Entropy::Algorithms::rand_bits(128) is used to generate the salt. The code is verified to be correct. There is an issue in version 1.208 of the module.

**Comment by genio** [comment]
I apologize for the error and annoyance it caused.  I've reverted the change that broke your situation and added author tests to try to ensure that I don't accidentally re-introduce it in the future.  I'll cut a release shortly.
