### ISSUE TITLE
Switch to modern bcrypt implementation

### ISSUE THREAD

**Issue by Leont** [genio/digest-bcrypt#5]
This module is currently using `Crypt::Eksblowfish::Bcrypt` which is essentially unmaintained for the past decade. In particular, the rest of the world upgraded to the `2b` variety of bcrypt back in 2014.

I've recently released [Crypt::Bcrypt](https://metacpan.org/pod/Crypt::Bcrypt), which does support modern varieties of bcrypt.

**Comment by genio** [comment]
This has been done and released.  Thanks! https://metacpan.org/release/CAPOEIRAB/Digest-Bcrypt-1.210
