### ISSUE TITLE
New cost requirement can break existing clients

### ISSUE THREAD

**Issue by vitahall** [genio/digest-bcrypt#7]
The new minimum cost of 5 associated with Crypt::Bcrypt breaks clients that assume they can pass a cost < 5, for example [Dancer2::Plugin::Passphrase](https://metacpan.org/pod/Dancer2::Plugin::Passphrase), whose default is a cost of 4.

I'm not familiar enough with Bcrypt to know for sure, but maybe it's possible to silently (or with a warning) pin an out-of-range cost to the acceptable input range.

**Comment by genio** [comment]
@Leont Thoughts?

**Comment by Leont** [comment]
It seems this is a small mistake on my part, 4 is the lowest allowed value not 5. I'll update that.

That said, `4` is a terribly low value, and for security reasons one should be using something higher really.

**Comment by Leont** [comment]
Fixed in Crypt::Bcrypt 0.006
